# Generated by Django 6.0.4 on 2026-04-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.TextField(blank=True, default='', help_text="Cloudinary URL for the user's profile picture"),
        ),
    ]
