# Generated by Django 6.0.3 on 2026-04-06 20:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0003_alter_wallettransaction_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tenure_months', models.PositiveIntegerField(help_text='Repayment period in months (max 11)')),
                ('interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0.005'), help_text='Monthly interest rate at time of application', max_digits=6)),
                ('total_repayable', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_approved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_rolled_over', models.BooleanField(default=False, help_text='True if wallet had insufficient funds')),
                ('extra_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Accumulated penalty interest from rollovers', max_digits=14)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='loan.loan')),
                ('wallet_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayment_schedule', to='wallet.wallettransaction')),
            ],
            options={
                'ordering': ['installment_number'],
                'unique_together': {('loan', 'installment_number')},
            },
        ),
    ]
