# Generated by Django 6.0.3 on 2026-04-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepaymentschedule',
            name='is_rolled_over',
            field=models.BooleanField(default=False, help_text='True if wallet had insufficient funds on due date'),
        ),
    ]
