# Generated by Django 6.0.3 on 2026-04-25 08:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loanrepaymentschedule_is_rolled_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.5'), help_text='Monthly interest rate at time of application', max_digits=6),
        ),
    ]
