# Generated by Django 6.0.3 on 2026-03-07 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=10)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('land', 'Land')], max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('sold', 'Sold'), ('rented', 'Rented')], default='available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allows_installment', models.BooleanField(default=False)),
                ('installment_duration_months', models.PositiveIntegerField(blank=True, help_text='Max duration allowed for installmental payment (months)', null=True)),
                ('minimum_initial_deposit', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum deposit to initiate an installment purchase', max_digits=14, null=True)),
                ('rent_duration', models.CharField(blank=True, help_text='Duration of the rental agreement (e.g., 1 year)', max_length=50, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('toilets', models.PositiveIntegerField(blank=True, null=True)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Total land/floor area in square metres', max_digits=10, null=True)),
                ('is_furnished', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
