# Generated by Django 6.0.3 on 2026-03-25 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('INITIAL_ADMIN_SET', 'Initial admin set'), ('USER_TOPUP', 'User top-up'), ('ADMIN_ADJUSTMENT', 'Admin adjustment'), ('WITHDRAWAL', 'Withdrawal'), ('PURCHASE', 'Purchase'), ('TRANSFER', 'Transfer')], max_length=30),
        ),
        migrations.CreateModel(
            name='WalletPaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image_url', models.TextField(blank=True, default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof', to='wallet.wallettransaction')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_payment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_payment_proof',
            },
        ),
    ]
