# Generated by Django 6.0.3 on 2026-04-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallettransaction_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('INITIAL_ADMIN_SET', 'Initial admin set'), ('USER_TOPUP', 'User top-up'), ('ADMIN_ADJUSTMENT', 'Admin adjustment'), ('WITHDRAWAL', 'Withdrawal'), ('PURCHASE', 'Purchase'), ('TRANSFER', 'Transfer'), ('LOAN_REPAYMENT', 'Loan repayment')], max_length=30),
        ),
    ]
