# Generated by Django 6.0.3 on 2026-04-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallettransaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('INITIAL_ADMIN_SET', 'Initial admin set'), ('USER_TOPUP', 'User top-up'), ('ADMIN_ADJUSTMENT', 'Admin adjustment'), ('WITHDRAWAL', 'Withdrawal'), ('PURCHASE', 'Purchase'), ('TRANSFER', 'Transfer'), ('LOAN_REPAYMENT', 'Loan repayment'), ('LOAN_DISBURSEMENT', 'Loan Disbursement')], max_length=30),
        ),
    ]
