# Generated by Django 6.0.3 on 2026-04-25 08:28

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0002_alter_listing_rent_duration'),
        ('wallet', '0004_wallettransaction_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purchase_type', models.CharField(choices=[('OUTRIGHT', 'Outright'), ('INSTALLMENT', 'Installment')], max_length=15)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('initial_deposit', models.DecimalField(blank=True, decimal_places=2, help_text='Deposit paid upfront to kick off the installment plan', max_digits=14, null=True)),
                ('balance_after_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tenure_months', models.PositiveIntegerField(blank=True, help_text='Installment duration in months', null=True)),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_repayable', models.DecimalField(blank=True, decimal_places=2, help_text='balance_after_deposit (no interest — property purchase, not a loan)', max_digits=14, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_approved', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInstallmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_overdue', models.BooleanField(default=False, help_text='Flagged by the scheduler when due_date passes without payment')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='purchase.purchase')),
                ('wallet_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_installment', to='wallet.wallettransaction')),
            ],
            options={
                'ordering': ['installment_number'],
                'unique_together': {('purchase', 'installment_number')},
            },
        ),
    ]
